services:
  app-dev:
    build:
      context: .
      dockerfile: deploy/Dockerfile
      args:
        - ENV=dev
    container_name: app
    image: irdaislakhuafa/billing-engine:latest
    ports:
      - 8001:8001
    tty: true
    stdin_open: true
    networks:
      - app
    depends_on:
      - db
  db:
    image: mysql:8.0.26
    container_name: dbapp
    ports:
      - 3306:3306
    volumes:
      - ./docs/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=vznI6F2FKNwr0sdw
      - MYSQL_DATABASE=amartha_billing
    networks:
      - app

networks:
  app: {}
  
      
