
[[language]]
auto-format = true
comment-token = "//"
language-servers = ["gopls", "scls"]
name = "go"
roots = ["go.mod", "go.sum", "go.work"]

[language.block-comment-tokens]
end = "*/"
start = "/*"

[language.formatter]
command = "goimports"

[language.indent]
tab-width = 2
unit = " "

[language-server.gopls]
command = "gopls"
scope = "source.go"

[language-server.gopls.config]
completeUnimported = true
gofumpt = true
local = "goimports"
semanticTokens = true
staticcheck = true
usePlaceholders = true
verboseOutput = true
[language-server.gopls.config.analyses]
fieldalignment = true
nilness = true
unusedparams = true
unusedwrite = true
useany = true

[language-server.gopls.config.hints]
assignVariableType = true
compositeLiteralFields = true
compositeLiteralTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
citation = true
feature_citations = true
feature_paths = true
feature_snippets = true
feature_unicode_input = true
feature_words = true
max_completion_items = 100
snippets_first = true
snippets_inline_by_word_tail = true
